services:
  proton-tkg:
    build: ./
    container_name: proton-tkg-builder
    volumes:
      - .build:/proton-tkg:rw
      - ./patches:/patches:rw
    working_dir: /proton-tkg
    stdin_open: true
    tty: true
    command: bash -c "
          paru -Syu --noconfirm && \
          export CARGO_HOME="$PWD" && \
          rm -rf * && \
          git clone https://github.com/Frogging-Family/wine-tkg-git.git && \
          cd wine-tkg-git && \
          cd proton-tkg && \
          
          sed -i 's/uninstaller=\"false\"/uninstaller=\"true\"/' proton-tkg.cfg && \
          sed -i 's/autoinstall=\"false\"/autoinstall=\"true\"/' proton-tkg.cfg && \
          sed -i 's/LOCAL_PRESET=\"\"/LOCAL_PRESET=\"none\"/' proton-tkg.cfg && \
          sed -i 's/_build_gstreamer=\"false\"/_build_gstreamer=\"true\"/' proton-tkg.cfg && \
          sed -i 's/lib32_gstreamer=\"false\"/lib32_gstreamer=\"true\"/' proton-tkg.cfg && \
          sed -i 's/wayland_driver=\"false\"/wayland_driver=\"true\"/' proton-tkg.cfg && \
          sed -i 's/_use_ntsync=\"false\"/_use_ntsync=\"true\"/' proton-tkg.cfg && \
          sed -i 's/_use_esync=\"true\"/_use_esync=\"false\"/' proton-tkg.cfg && \
          sed -i 's/_use_fsync=\"true\"/_use_fsync=\"false\"/' proton-tkg.cfg && \
          sed -i 's/_user_patches_no_confirm=\"false\"/_user_patches_no_confirm=\"true\"/' proton-tkg.cfg && \

          cd proton-tkg-profiles && \
          sed -i 's/_proton_branch=\"experimental_8.0\"/_proton_branch=\"experimental_9.0\"/' advanced-customization.cfg && \
          sed -i 's/_sdl_joy_support=\"false\"/_sdl_joy_support=\"true\"/' advanced-customization.cfg && \

          cd .. && \
          cp /patches/* ../wine-tkg-git/wine-tkg-userpatches && \
          touch tarplz && \
          yes|./proton-tkg.sh"

