name: Build Proton-TKG with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-proton-tkg:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: pacman -Syu --noconfirm && pacman -S --noconfirm docker docker-compose

      - name: Build Proton-TKG with Docker Compose
        run: docker-compose up --build

      - name: Monitor the build logs (optional)
        run: docker-compose logs -f

      - name: Stop and clean up containers
        run: docker-compose down

      - name: Save build artifacts (if needed)
        run: |
          mkdir -p artifacts
          cp build/wine-tkg-git/proton-tkg/built/*  artifacts/
        if: success()

      - name: Upload built Proton-TKG as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: artifacts/