name: Build Proton-TKG with Docker Compose

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-proton-tkg:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: pacman -Syu --noconfirm && pacman -S --noconfirm docker docker-compose

      - name: Files
        run: | 
          pwd
          ls -la
          ls patches
          echo "-------patches-----"
          echo ${{ github.workspace }}

      - name: Build Proton-TKG with Docker Compose
        working-directory: ${{ github.workspace }}
        run: docker-compose up --build

      - name: Save build artifacts (if needed)
        run: |
          mkdir -p artifacts
          cp build/wine-tkg-git/proton-tkg/built/*  artifacts/
        if: success()

      - name: Upload built Proton-TKG as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: artifacts/